### ISSUE TITLE
Megaissue - planned upgrade work

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/customerio-plugin#39]
# Problems

> Gathering the issues here as we will likely try and solve this in a way that is more holistic rather than patching existing broken behaviours

- [ ] *Person Profile needed for email* - [issue](https://github.com/PostHog/customerio-plugin/issues/26) [ticket](https://posthoghelp.zendesk.com/agent/tickets/12637) [ticket](https://posthoghelp.zendesk.com/agent/tickets/10322) [ticket](https://posthoghelp.zendesk.com/agent/tickets/10285)
- [ ] *Anonymous user IDs* - [ticket](https://posthoghelp.zendesk.com/agent/tickets/12635)
  - [ ] Way to specify what property to use as the ID and whether to ignore it if not found
  - [ ] Maybe we should only ever send identified users?
- [ ] *Group support* -  [issue](https://github.com/PostHog/customerio-plugin/issues/34) 
- [ ] *Event filtering* - [issue](https://github.com/PostHog/customerio-plugin/issues/36) [issue](https://github.com/PostHog/customerio-plugin/issues/11)
  - [ ] Could ideally be done with the new Action filtering UI rather than in code

**Comment by tiina303** [comment]
Haven't  figured out the details of this ticket, but just to make sure we won't forget https://posthoghelp.zendesk.com/agent/tickets/13230

**Comment by acarsw** [comment]
https://customer7760.zendesk.com/agent/tickets/106906

**Comment by niels-bosman** [comment]
@benjackwhite @tiina303 Does this include filtering events from users that have specific properties? We don’t want to send free users to customer.io, but we do want to send premium users. This is a field on the user in PostHog.

**Comment by benjackwhite** [comment]
> Does this include filtering events from users that have specific properties? We don’t want to send free users to customer.io, but we do want to send premium users. This is a field on the user in PostHog.

That's the idea of what we are doing. We are hoping to have this out in feature preview this week. Our new delivery system supersedes the plugin concept and has a bunch of nice features such as generic filtering, input template strings and in the end the ability to just modify the underlying code which gives ultimate flexibility (at the cost of having to write some code).

Sneak preview of what it looks like here: 
<img width="1366" alt="Screenshot 2024-07-23 at 12 40 17" src="https://github.com/user-attachments/assets/eed4f9d6-0931-4078-9ee0-671fbe24a34a">

**Comment by niels-bosman** [comment]
@benjackwhite Amazing, would love to try it ASAP as we have a lot of customers we're adding to Customer.io now that we will have to manually delete :D

Great work guys

**Comment by niels-bosman** [comment]
Any updates on this?

**Comment by gregegan** [comment]
Is this new system ready to go @benjackwhite? Would love to give implement it.
